# Makefile — Deployment Decision Engine
# ========================================
# Reproducibility and verification commands.
# Requires: docker, GNU make, bash.
#
# Usage:
#   make build              — build deterministic container (from local wheels)
#   make pin-digest         — patch Dockerfile FROM with live image digest
#   make freeze-wheels      — download wheels + generate wheels.sha256
#   make verify-wheels      — verify wheel archive integrity
#   make wheel-hashes       — alias for verify-wheels
#   make test               — run golden tests inside container
#   make reproduce          — full end-to-end reproducibility check
#   make hashes             — generate SHA256 for all model artefacts
#   make verify-hashes      — verify model artefact integrity
#   make fingerprint        — generate environment fingerprint locally
#   make fingerprint-from-container — extract fingerprint from built container
#   make verify-fingerprint — check environment against stored fingerprint
#   make golden-update      — regenerate golden baseline outputs
#   make golden-diff        — diff current outputs against stored baseline
#   make bundle             — assemble the immutable runtime_bundle/
#   make ci                 — full CI pipeline (mirrors .github/workflows/ci.yml)
#   make clean              — remove container image and cache

IMAGE_NAME   := dde
IMAGE_TAG    := latest
CONTAINER    := $(IMAGE_NAME):$(IMAGE_TAG)

PYTHON       := python
PYTEST_FLAGS := -v --tb=short

DIGEST_FILE  := runtime_bundle/container_digest.txt
WHEELS_DIR   := wheels
HASH_FILE    := wheels.sha256

.PHONY: build pin-digest freeze-wheels verify-wheels wheel-hashes \
        test test-local reproduce \
        hashes verify-hashes fingerprint fingerprint-from-container \
        verify-fingerprint golden-update golden-diff \
        bundle ci clean help

# ── STEP 1: Pin Docker image digest ───────────────────────────────────────

pin-digest:
	@echo "==> Pulling python:3.10.13-slim to obtain exact digest..."
	docker pull python:3.10.13-slim
	$(eval DIGEST := $(shell docker inspect --format='{{index .RepoDigests 0}}' python:3.10.13-slim))
	@echo "==> Digest: $(DIGEST)"
	@# Patch Dockerfile FROM line
	sed -i.bak 's|FROM python@sha256:[a-f0-9]*|FROM $(DIGEST)|' Dockerfile
	@rm -f Dockerfile.bak
	@# Patch runtime_bundle/container_digest.txt
	@mkdir -p runtime_bundle
	@printf '# runtime_bundle/container_digest.txt\n# Auto-generated by: make pin-digest\n$(DIGEST)\n' \
	    > $(DIGEST_FILE)
	@echo "==> Dockerfile FROM and $(DIGEST_FILE) updated."
	@echo "==> Commit both files to the repository."

# ── STEP 5+6: Wheel management ────────────────────────────────────────────

freeze-wheels:
	@echo "==> STEP 5: Downloading pre-frozen wheels for linux/amd64 Python 3.10..."
	@echo "==> NOTE: This must run on linux/amd64 or inside a linux/amd64 container."
	bash scripts/freeze_wheels.sh
	@echo "==> Wheel archive ready. Commit wheels/ and wheels.sha256."

verify-wheels:
	@echo "==> STEP 6: Verifying wheel archive integrity..."
	bash scripts/verify_wheels.sh
	@echo "==> Wheel archive OK."

wheel-hashes: verify-wheels

# ── Container ─────────────────────────────────────────────────────────────

build: verify-wheels
	@echo "==> Building deterministic container (no cache, local wheels only)..."
	docker build --no-cache -t $(CONTAINER) .
	@echo "==> Build complete: $(CONTAINER)"

# ── Tests ─────────────────────────────────────────────────────────────────

test:
	@echo "==> Running golden tests inside container..."
	docker run --rm \
	    -e PYTHONHASHSEED=0 \
	    -e OMP_NUM_THREADS=1 \
	    -e MKL_NUM_THREADS=1 \
	    -e OPENBLAS_NUM_THREADS=1 \
	    -e OPENBLAS_CORETYPE=HASWELL \
	    -e MKL_CBWR=COMPATIBLE \
	    -e CUDA_VISIBLE_DEVICES="" \
	    $(CONTAINER) \
	    $(PYTHON) -m pytest tests/golden/test_golden_baseline.py $(PYTEST_FLAGS)

test-local:
	@echo "==> Running golden tests locally (not in container — for development only)..."
	$(PYTHON) -m pytest tests/golden/test_golden_baseline.py $(PYTEST_FLAGS)

# ── Reproducibility ───────────────────────────────────────────────────────

reproduce: build verify-hashes verify-fingerprint test
	@echo "==> Reproducibility check PASSED"

# ── Model artefact integrity ──────────────────────────────────────────────

hashes:
	@echo "==> Computing SHA256 for all model artefacts..."
	$(PYTHON) scripts/generate_hashes.py
	@echo "==> Hashes written to model_hashes.sha256"

verify-hashes:
	@echo "==> Verifying model artefact integrity..."
	$(PYTHON) scripts/verify_hashes.py
	@echo "==> All model hashes verified OK"

# ── Environment fingerprint ───────────────────────────────────────────────

fingerprint:
	@echo "==> Generating deep environment fingerprint locally..."
	$(PYTHON) scripts/generate_fingerprint.py --output fingerprint.json
	@cat fingerprint.json
	@echo "==> WARNING: For the authoritative fingerprint, use fingerprint-from-container"

fingerprint-from-container:
	@echo "==> Extracting deep fingerprint from built container..."
	docker run --rm \
	    -e PYTHONHASHSEED=0 \
	    -e OMP_NUM_THREADS=1 \
	    -e MKL_NUM_THREADS=1 \
	    -e OPENBLAS_NUM_THREADS=1 \
	    -e OPENBLAS_CORETYPE=HASWELL \
	    -e MKL_CBWR=COMPATIBLE \
	    -e CUDA_VISIBLE_DEVICES="" \
	    -v "$(PWD):/host" \
	    $(CONTAINER) \
	    sh -c "python scripts/generate_fingerprint.py --output /tmp/fp.json && cp /tmp/fp.json /host/fingerprint.json"
	@echo "==> fingerprint.json updated from container."
	@cat fingerprint.json

verify-fingerprint:
	@echo "==> Checking deep environment against stored fingerprint..."
	$(PYTHON) scripts/verify_fingerprint.py --expected fingerprint.json --strict

# ── STEP 11: Runtime gate smoke test ─────────────────────────────────────

runtime-gate:
	@echo "==> STEP 11: Testing runtime gate (container + fingerprint + hashes)..."
	docker run --rm \
	    -e PYTHONHASHSEED=0 \
	    -e OMP_NUM_THREADS=1 \
	    -e MKL_NUM_THREADS=1 \
	    -e OPENBLAS_NUM_THREADS=1 \
	    -e OPENBLAS_CORETYPE=HASWELL \
	    -e MKL_CBWR=COMPATIBLE \
	    -e CUDA_VISIBLE_DEVICES="" \
	    -e MODEL_HASH_VERIFY=1 \
	    -e ENV_CHECK_STRICT=1 \
	    $(CONTAINER) \
	    $(PYTHON) -c \
	        "from src.env_check import verify_environment; verify_environment(); print('Runtime gate: PASSED')"

# ── Golden baseline management ───────────────────────────────────────────

golden-update:
	@echo "==> WARNING: Regenerating golden baseline outputs!"
	@echo "==> This must be reviewed and approved before committing."
	$(PYTHON) scripts/generate_golden.py --output tests/golden/baseline/

golden-diff:
	@echo "==> Diffing current outputs against stored baseline..."
	$(PYTHON) scripts/diff_golden.py --baseline tests/golden/baseline/

# ── STEP 10: Immutable runtime bundle ────────────────────────────────────

bundle: freeze-wheels build fingerprint-from-container hashes
	@echo "==> Assembling immutable runtime_bundle/..."
	mkdir -p runtime_bundle/wheels
	cp requirements.lock        runtime_bundle/requirements.lock
	cp wheels.sha256            runtime_bundle/wheels.sha256
	cp fingerprint.json         runtime_bundle/fingerprint.json
	cp model_hashes.sha256      runtime_bundle/model_hashes.sha256
	rsync -a --delete wheels/   runtime_bundle/wheels/
	@echo "$(shell docker inspect --format='{{index .RepoDigests 0}}' $(CONTAINER) 2>/dev/null || \
	              cat $(DIGEST_FILE) | grep -v '^#' | head -1)" \
	    > runtime_bundle/container_digest.txt
	@echo "==> runtime_bundle/ contents:"
	@ls -lh runtime_bundle/
	@echo "==> Bundle complete. Treat runtime_bundle/ as an atomic, immutable unit."

# ── CI simulation ─────────────────────────────────────────────────────────

ci: verify-wheels build verify-hashes verify-fingerprint test runtime-gate
	@echo "==> CI pipeline PASSED — system is bounded-deterministic"

# ── Utilities ─────────────────────────────────────────────────────────────

clean:
	docker rmi $(CONTAINER) 2>/dev/null || true
	find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
	find . -name "*.pyc" -delete 2>/dev/null || true

help:
	@echo ""
	@echo "Deployment Decision Engine — Build Targets"
	@echo "==========================================="
	@echo "  pin-digest                 Patch Dockerfile FROM with live image digest"
	@echo "  freeze-wheels              Download wheels + generate wheels.sha256"
	@echo "  verify-wheels              Verify wheel archive integrity"
	@echo "  build                      Build deterministic container (local wheels)"
	@echo "  fingerprint                Generate fingerprint locally"
	@echo "  fingerprint-from-container Extract fingerprint from built container"
	@echo "  verify-fingerprint         Verify environment against stored fingerprint"
	@echo "  hashes                     Generate model artefact SHA256"
	@echo "  verify-hashes              Verify model artefact hashes"
	@echo "  test                       Run golden tests in container"
	@echo "  runtime-gate               Smoke-test the full startup gate"
	@echo "  bundle                     Assemble immutable runtime_bundle/"
	@echo "  reproduce                  Full reproducibility check"
	@echo "  ci                         Full CI pipeline"
	@echo "  clean                      Remove container + caches"
	@echo ""

# ── ML v2 training targets ────────────────────────────────────────────────

.PHONY: train-v2 train-v2-ranking collect-v2-data test-v2-smoke

collect-v2-data: ## Collect benchmark data for v2 training
	python -m src.training.data_collector \
		--output data/benchmark_results.parquet

train-v2: ## Train the v2 multi-head PyTorch model
	python -m src.training.train \
		--parquet data/benchmark_results.parquet \
		--model-features data/model_features.pkl \
		--output model_bundle_v2/decision_net.pt \
		--epochs 50 \
		--batch-size 64 \
		--lr 3e-4

train-v2-ranking: ## Train the v2 ranking ensemble model
	python -m src.training.ranking_train \
		--parquet data/benchmark_results.parquet \
		--output model_bundle_v2/ranking_ensemble.pt \
		--epochs 40

test-v2-smoke: ## Smoke-test the v2 pipeline (requires trained model_bundle_v2/)
	python -c "\
from pathlib import Path; \
from src.inference.pipeline import InferencePipeline; \
p = InferencePipeline.from_bundle_dir(Path('model_bundle_v2/')); \
r = p.predict(model_facts={'parameter_count':1000000,'operator_count':50,'has_dynamic_shapes':False,'parameter_scale_class':'small','model_size_mb':4.0,'sequential_depth_estimate':30,'has_conv':True,'has_attention':False,'has_resize':False,'uses_batch_normalization':True,'uses_layer_normalization':False,'has_non_max_suppression':False,'has_conv_transpose':False},deployment_profile={'cpu_cores':4,'ram_gb':8.0,'gpu_available':False,'cuda_available':False}); \
print('best_runtime:', r.best_runtime); print('confidence:', round(r.confidence,4)); print('PASS')"
